rmdir "SINGLECODEBASE\SINGLECODEBASE\bin" /Q /S
rmdir "SINGLECODEBASE\SINGLECODEBASE\obj" /Q /S

rmdir "SINGLECODEBASE\SINGLECODEBASE.Shared\bin" /Q /S
rmdir "SINGLECODEBASE\SINGLECODEBASE.Shared\obj" /Q /S

rmdir "SINGLECODEBASE\SINGLECODEBASE.Web\bin" /Q /S
rmdir "SINGLECODEBASE\SINGLECODEBASE.Web\obj" /Q /S

rmdir "SINGLECODEBASE\SINGLECODEBASE.Web.Client\bin" /Q /S
rmdir "SINGLECODEBASE\SINGLECODEBASE.Web.Client\obj" /Q /S
